-- ─────────────────────────────────────────────────────────────────────────────
-- O que ainda falta rodar no banco
--
-- NÃO É MIGRATION. Só consulta — não cria nem altera nada.
--
-- Por que existe: oito números de migration foram usados DUAS vezes por
-- agentes diferentes (015, 016, 017, 021, 022, 023, 065, 066). Quem rodou
-- "a 065" rodou uma das duas e a outra ficou para trás, sem ninguém notar —
-- até o app dar erro, como aconteceu com `transfer_routes.cover_image_url`.
--
-- Esta consulta compara TODAS as colunas que as migrations adicionam com o que
-- existe hoje no banco. O que aparecer é o que falta.
-- ─────────────────────────────────────────────────────────────────────────────

WITH esperado(tabela, coluna, migration) AS (VALUES
  ('bookings', 'acceptance_expires_at', '037_booking_acceptance_window.sql'),
  ('bookings', 'admin_notified_expired_at', '038_booking_admin_notify_flag.sql'),
  ('bookings', 'destination_latitude', '002_locations_and_quotes.sql'),
  ('bookings', 'destination_longitude', '002_locations_and_quotes.sql'),
  ('bookings', 'destination_place_id', '002_locations_and_quotes.sql'),
  ('bookings', 'destination_place_name', '002_locations_and_quotes.sql'),
  ('bookings', 'operator_id', '014_booking_operator.sql'),
  ('bookings', 'order_group_id', '050_order_group.sql'),
  ('bookings', 'payment_deadline_at', '047_leg_partial_checkout_flow.sql'),
  ('bookings', 'pickup_latitude', '002_locations_and_quotes.sql'),
  ('bookings', 'pickup_longitude', '002_locations_and_quotes.sql'),
  ('bookings', 'pickup_place_id', '002_locations_and_quotes.sql'),
  ('bookings', 'pickup_place_name', '002_locations_and_quotes.sql'),
  ('bookings', 'service_datetime', '042_booking_legs_split_engine.sql'),
  ('commissions', 'leg_id', '042_booking_legs_split_engine.sql'),
  ('commissions', 'operator_id', '042_booking_legs_split_engine.sql'),
  ('establishments', 'latitude', '025_establishments_coords.sql'),
  ('establishments', 'locality', '018_establishments_seed.sql'),
  ('establishments', 'longitude', '025_establishments_coords.sql'),
  ('establishments', 'price_note', '018_establishments_seed.sql'),
  ('establishments', 'region_id', '023_establishments_region.sql'),
  ('establishments', 'region_ids', '027_establishment_multi_region.sql'),
  ('feed_posts', 'discount_label', '017_establishments_and_promos.sql'),
  ('feed_posts', 'kind', '017_establishments_and_promos.sql'),
  ('feed_posts', 'valid_until', '017_establishments_and_promos.sql'),
  ('financial_ledger', 'leg_id', '042_booking_legs_split_engine.sql'),
  ('notifications', 'read_at', '021_notifications_read_and_push.sql'),
  ('operational_assignments', 'driver_name', '017_assignment_driver_contact.sql'),
  ('operational_assignments', 'driver_paid_at', '066_driver_payouts.sql'),
  ('operational_assignments', 'driver_payout_amount', '066_driver_payouts.sql'),
  ('operational_assignments', 'driver_payout_notes', '066_driver_payouts.sql'),
  ('operational_assignments', 'driver_payout_status', '066_driver_payouts.sql'),
  ('operational_assignments', 'driver_phone', '017_assignment_driver_contact.sql'),
  ('payments', 'card_brand', '024_card_payment_columns.sql'),
  ('payments', 'card_holder_name', '024_card_payment_columns.sql'),
  ('payments', 'card_last_four', '024_card_payment_columns.sql'),
  ('payments', 'gateway_fee_pct', '024_card_payment_columns.sql'),
  ('payments', 'installment_fee_amount', '024_card_payment_columns.sql'),
  ('payments', 'installments', '024_card_payment_columns.sql'),
  ('payments', 'ledger_created', '021_payment_ledger_idempotency.sql'),
  ('payments', 'order_group_id', '050_order_group.sql'),
  ('reviews', 'operator_id', '060_coop_reviews.sql'),
  ('stories', 'highlight_id', '030_story_highlights.sql'),
  ('tours', 'booking_cutoff_time', '015_tour_cutoff_time.sql'),
  ('tours', 'is_exclusive', '051_tour_exclusive.sql'),
  ('tours', 'latitude', '008_service_geofiltering.sql'),
  ('tours', 'longitude', '008_service_geofiltering.sql'),
  ('tours', 'min_advance_hours', '049_service_min_advance_hours.sql'),
  ('tours', 'region_ids', '028_catalog_multi_region.sql'),
  ('tours', 'service_radius_km', '008_service_geofiltering.sql'),
  ('tours', 'service_window_end', '069_service_time_window.sql'),
  ('tours', 'service_window_start', '069_service_time_window.sql'),
  ('transfer_routes', 'cover_image_url', '065_route_cover_image.sql'),
  ('transfer_routes', 'destination_place_id', '002_locations_and_quotes.sql'),
  ('transfer_routes', 'destination_place_name', '002_locations_and_quotes.sql'),
  ('transfer_routes', 'is_featured', '059_featured_routes.sql'),
  ('transfer_routes', 'origin_place_id', '002_locations_and_quotes.sql'),
  ('transfer_routes', 'origin_place_name', '002_locations_and_quotes.sql'),
  ('transfers', 'booking_cutoff_time', '015_tour_cutoff_time.sql'),
  ('transfers', 'is_exclusive', '067_translados_aereos_exclusivos.sql'),
  ('transfers', 'latitude', '008_service_geofiltering.sql'),
  ('transfers', 'longitude', '008_service_geofiltering.sql'),
  ('transfers', 'min_advance_hours', '049_service_min_advance_hours.sql'),
  ('transfers', 'region_ids', '028_catalog_multi_region.sql'),
  ('transfers', 'service_radius_km', '008_service_geofiltering.sql'),
  ('transfers', 'service_window_end', '069_service_time_window.sql'),
  ('transfers', 'service_window_start', '069_service_time_window.sql'),
  ('users', 'address', '016_operator_address.sql'),
  ('users', 'affiliate_code', '055_affiliate_program.sql'),
  ('users', 'affiliate_pix_key', '056_affiliate_pix_key.sql'),
  ('users', 'affiliate_pix_key_type', '056_affiliate_pix_key.sql'),
  ('users', 'bank_account_number', '009_operator_banking.sql'),
  ('users', 'bank_account_type', '009_operator_banking.sql'),
  ('users', 'bank_agency', '009_operator_banking.sql'),
  ('users', 'bank_document', '009_operator_banking.sql'),
  ('users', 'bank_name', '009_operator_banking.sql'),
  ('users', 'cep', '016_operator_address.sql'),
  ('users', 'cover_photo_url', '015_profile_cover_and_home_banner.sql'),
  ('users', 'document_type', '003_tourist_profile_fields.sql'),
  ('users', 'email_verified_at', '023_otp_verification.sql'),
  ('users', 'emergency_contact_email', '058_emergency_email.sql'),
  ('users', 'emergency_contact_name', '003_tourist_profile_fields.sql'),
  ('users', 'emergency_contact_phone', '003_tourist_profile_fields.sql'),
  ('users', 'gateway_recipient_id', '013_gateway_recipient_id.sql'),
  ('users', 'gender', '003_tourist_profile_fields.sql'),
  ('users', 'marketing_opt_out', '068_coupon_broadcast.sql'),
  ('users', 'marketing_opt_out_at', '068_coupon_broadcast.sql'),
  ('users', 'mfa_enabled', '063_mfa.sql'),
  ('users', 'mp_access_token', '036_mp_marketplace_connection.sql'),
  ('users', 'mp_connected_at', '036_mp_marketplace_connection.sql'),
  ('users', 'mp_payout_exempt', '070_operator_mp_required.sql'),
  ('users', 'mp_public_key', '036_mp_marketplace_connection.sql'),
  ('users', 'mp_refresh_token', '036_mp_marketplace_connection.sql'),
  ('users', 'mp_token_expires_at', '036_mp_marketplace_connection.sql'),
  ('users', 'mp_user_id', '036_mp_marketplace_connection.sql'),
  ('users', 'nationality', '003_tourist_profile_fields.sql'),
  ('users', 'partner_slug', '054_partner_slug.sql'),
  ('users', 'phone_e164', '023_otp_verification.sql'),
  ('users', 'phone_verified_at', '023_otp_verification.sql'),
  ('users', 'pix_key', '009_operator_banking.sql'),
  ('users', 'pix_key_type', '009_operator_banking.sql'),
  ('users', 'platform_split_pct', '012_operator_split_pct.sql'),
  ('users', 'username', '061_user_username.sql'),
  ('users', 'whatsapp_checked_at', '057_whatsapp_validation.sql'),
  ('users', 'whatsapp_valid', '057_whatsapp_validation.sql'),
  ('vehicles', 'latitude', '008_service_geofiltering.sql'),
  ('vehicles', 'longitude', '008_service_geofiltering.sql'),
  ('vehicles', 'region_ids', '028_catalog_multi_region.sql'),
  ('vehicles', 'requires_opt_in', '066_vehicle_requires_opt_in.sql'),
  ('vehicles', 'service_radius_km', '008_service_geofiltering.sql')
)
SELECT e.migration        AS rodar_esta_migration,
       e.tabela,
       e.coluna
FROM esperado e
JOIN information_schema.tables t
  ON t.table_schema = 'public' AND t.table_name = e.tabela
LEFT JOIN information_schema.columns c
  ON c.table_schema = 'public' AND c.table_name = e.tabela AND c.column_name = e.coluna
WHERE c.column_name IS NULL
ORDER BY e.migration, e.tabela, e.coluna;
